package com.test.domain;

// default package
// Generated 30-jul-2015 14:50:51 by Hibernate Tools 3.4.0.CR1

/**
 * Lineacompra generated by hbm2java
 */
public class Lineacompra implements java.io.Serializable {

	private Integer id;
	private int idProducto;
	private int cantidad;
	private float total;

	public Lineacompra() {
	}

	public Lineacompra(int idProducto, int cantidad, float total) {
		this.idProducto = idProducto;
		this.cantidad = cantidad;
		this.total = total;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

}
