package com.test.domain;

// default package
// Generated 30-jul-2015 14:50:51 by Hibernate Tools 3.4.0.CR1

/**
 * Pagofactura generated by hbm2java
 */
public class Pagofactura implements java.io.Serializable {

	private Integer id;
	private int idPago;
	private int idFactura;

	public Pagofactura() {
	}

	public Pagofactura(int idPago, int idFactura) {
		this.idPago = idPago;
		this.idFactura = idFactura;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdPago() {
		return this.idPago;
	}

	public void setIdPago(int idPago) {
		this.idPago = idPago;
	}

	public int getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(int idFactura) {
		this.idFactura = idFactura;
	}

}
