package com.test.domain;

// default package
// Generated 30-jul-2015 14:50:51 by Hibernate Tools 3.4.0.CR1

/**
 * Tipofactura generated by hbm2java
 */
public class Tipofactura implements java.io.Serializable {

	private Integer id;
	private char nombre;

	public Tipofactura() {
	}

	public Tipofactura(char nombre) {
		this.nombre = nombre;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public char getNombre() {
		return this.nombre;
	}

	public void setNombre(char nombre) {
		this.nombre = nombre;
	}

}
