package com.test.domain;

// default package
// Generated 30-jul-2015 14:50:51 by Hibernate Tools 3.4.0.CR1

/**
 * Tipodepago generated by hbm2java
 */
public class Tipodepago implements java.io.Serializable {

	private Integer id;
	private String nombre;

	public Tipodepago() {
	}

	public Tipodepago(String nombre) {
		this.nombre = nombre;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
